# @package model
defaults:
  - /model/conditioned_separation/base
  - /model/conditioned_separation/film
  - /model/conditioned_separation/tfc
_target_: lasaft.source_separation.conditioned.cunet.models.dcun_tfc_film.DCUN_TFC_FiLM_Framework

n_internal_layers: 5

kernel_size_t: 3
kernel_size_f: 3

tfc_activation: relu

