# @package model
defaults:
  - /model/conditioned_separation/base
  - /model/conditioned_separation/film
_target_: lasaft.source_separation.conditioned.cunet.models.dcun_tfc_film_tdf.DCUN_TFC_FiLM_TDF_Framework

n_internal_layers: 5

kernel_size_t: 3
kernel_size_f: 3

bn_factor: 16
min_bn_units: 16
tfc_tdf_bias: False
tfc_tdf_activation: relu
