defaults:
  - train_loss: spec_mse
  - val_loss: raw_l1
ckpt_root_path: 'etc/checkpoints'
log: True
run_id: ${now:%Y-%m-%d}/${now:%H-%M-%S}
save_weights_only: False
optimizer: adam
lr: 0.001
auto_lr_schedule: True
save_top_k: 5
patience: 10
seed: 2020